language: php
sudo: required
dist: trusty
php:
  - 5.6
  - 7.0
env:
  global:
    - CI=travis

install:
  - sudo apt-get update
  - sudo apt-get install xvfb libfontconfig wkhtmltopdf

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script:
  - phpunit --configuration phpunit.xml
